### PR TITLE
Added menu entry for preferences editing

### PR DESCRIPTION
**Pull request by crazybyte**
I added a menu entry for a more friendly editing of plugin preferences. It can be found in Preferences->Package Settings->SublimeManpage->Settings - Default. Thank you!

### CODE REVIEW

**Comment by crazybyte** [comment]
Thats very strange because on my machine the folder where the settings file resides is SublimeManpage.

**Comment by apophys** [comment]
Ok, don't apply that patch for now. I'll take a look at it.

**Comment by apophys** [comment]
Everything is ok, it was a glitch in my configuration. Sorry for confusion. :)

**Comment by crazybyte** [comment]
No problem. Thank you!

**Pull request merged**
